# Author: Al-assad
# Email: yulinying_1994@outlook.com
# Date: 2020-11-27
# Description: docker compose for clickhouse cluster with 3 shards and 1 relica, 1 zookeeper node

version: '2.1'

services:

  zookeeper:
    container_name: clickhouse-zookeeper
    hostname: zk1
    image: zookeeper:3.4
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.2
    ports:
      - published: 2181
        target: 2181


  clickhouse1:
    container_name: clickhouse-server-ch01
    depends_on:
      zookeeper:
        condition: service_started
    extra_hosts:
      - zk1:172.18.1.2
      - ch02:172.18.1.6
      - ch03:172.18.1.7
    hostname: ch01
    image: yandex/clickhouse-server:19.16.14.65
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.5
    ports:
      - published: 8124
        target: 8123
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    volumes:
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/ch-conf/metrika_ch01.xml:/etc/metrika.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/traffic-distribution.proto:/var/lib/clickhouse/format_schemas/traffic-distribution.proto:rw

  clickhouse2:
    container_name: clickhouse-server-ch02
    depends_on:
      zookeeper:
        condition: service_started
    extra_hosts:
      - zk1:172.18.1.2
      - ch01:172.18.1.5
      - ch03:172.18.1.7
    hostname: ch02
    image: yandex/clickhouse-server:19.16.14.65
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.6
    ports:
      - published: 8125
        target: 8123
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    volumes:
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/ch-conf/metrika_ch02.xml:/etc/metrika.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/traffic-distribution.proto:/var/lib/clickhouse/format_schemas/traffic-distribution.proto:rw

  clickhouse3:
    container_name: clickhouse-server-ch03
    depends_on:
      zookeeper:
        condition: service_started
    extra_hosts:
      - zk1:172.18.1.2
      - ch01:172.18.1.5
      - ch02:172.18.1.6
    hostname: ch03
    image: yandex/clickhouse-server:19.16.14.65
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.7
    ports:
      - published: 8126
        target: 8123
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    volumes:
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/ch-conf/metrika_ch03.xml:/etc/metrika.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml:rw
      - /Users/freedom/clickhouse/cluster/clickhouse-cluster-docker/traffic-distribution.proto:/var/lib/clickhouse/format_schemas/traffic-distribution.proto:rw

networks:
  clickhouse-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/16
